version: '3'
services:
  app:
    build: .
    ports:
      - '8000:8000'
    depends_on:
      - db
    env_file: .env
    networks:
      - mynetwork

  db:
    image: postgres
    ports:
      - '5432:5432'
    env_file: .env
    volumes:
      - ./app/data:/csv
      - ./db_init.sh:/docker-entrypoint-db_init.d/db_init.sh
    networks:
      - mynetwork

networks:
    mynetwork:
        driver: bridge